### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by stewi2** [stewi2/hadoop-lenient-sequencefile#1]
doesn't seem to happen with the "normal" SequenceFile reader.

``` java
2016-07-13 17:13:41,282 WARN [main] stewi.LenientSequenceFile: Detected truncated file: hdfs://americas/headphones_data/20160627/delta/help_center/help_center.requests/help_center.hedge1.sac1.zdsys.com.1466985601034.snappy, Shortened read buffer (102325235>325211)
2016-07-13 17:13:41,306 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.lang.IndexOutOfBoundsException
    at java.io.DataInputStream.readFully(DataInputStream.java:192)
    at org.apache.hadoop.io.DataOutputBuffer$Buffer.write(DataOutputBuffer.java:70)
    at org.apache.hadoop.io.DataOutputBuffer.write(DataOutputBuffer.java:120)
    at stewi.LenientSequenceFile$Reader.readBuffer(LenientSequenceFile.java:2121)
    at stewi.LenientSequenceFile$Reader.readBlock(LenientSequenceFile.java:2159)
    at stewi.LenientSequenceFile$Reader.next(LenientSequenceFile.java:2560)
    at stewi.mapred.LenientSequenceFileRecordReader.next(LenientSequenceFileRecordReader.java:85)
    at com.m6d.filecrush.crush.CrushReducer.reduce(CrushReducer.java:315)
    at com.m6d.filecrush.crush.CrushReducer.reduce(CrushReducer.java:47)
    at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:444)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:392)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

```

**Comment by yoelcabo** [comment]
I don't know if that is useful, but I am getting the exact same thing reading from a Sequence file using `hdfs dfs -text`

```
-text: Fatal internal error
java.lang.IndexOutOfBoundsException
    at java.io.DataInputStream.readFully(DataInputStream.java:192)
    at org.apache.hadoop.io.DataOutputBuffer$Buffer.write(DataOutputBuffer.java:70)
    at org.apache.hadoop.io.DataOutputBuffer.write(DataOutputBuffer.java:120)
    at org.apache.hadoop.io.SequenceFile$Reader.readBuffer(SequenceFile.java:2158)
    at org.apache.hadoop.io.SequenceFile$Reader.readBlock(SequenceFile.java:2197)
    at org.apache.hadoop.io.SequenceFile$Reader.next(SequenceFile.java:2359)
    at org.apache.hadoop.io.SequenceFile$Reader.next(SequenceFile.java:2388)
    at org.apache.hadoop.fs.shell.Display$TextRecordInputStream.read(Display.java:236)
    at java.io.InputStream.read(InputStream.java:179)
    at java.io.InputStream.read(InputStream.java:101)
    at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:91)
    at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:59)
    at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:119)
    at org.apache.hadoop.fs.shell.Display$Cat.printToStdout(Display.java:106)
    at org.apache.hadoop.fs.shell.Display$Cat.processPath(Display.java:101)
    at org.apache.hadoop.fs.shell.Command.processPaths(Command.java:317)
    at org.apache.hadoop.fs.shell.Command.processPathArgument(Command.java:289)
    at org.apache.hadoop.fs.shell.Command.processArgument(Command.java:271)
    at org.apache.hadoop.fs.shell.Command.processArguments(Command.java:255)
    at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:118)
    at org.apache.hadoop.fs.shell.Command.run(Command.java:165)
    at org.apache.hadoop.fs.FsShell.run(FsShell.java:315)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
    at org.apache.hadoop.fs.FsShell.main(FsShell.java:372)
```

Of course not with all the files. I guess this one was corrupted for some reason.
